import bedPng from '../assets/bed.png';
import tablePng from '../assets/table.png';
import billboardPng from '../assets/billboard.png';
import rocketBasePng from '../assets/rocketBase.png';
import rocketPng from '../assets/rocket.png';
import kitchenPng from '../assets/kitchen.png';
import musicPlayerPng from '../assets/musicPlayer.png';
import solarPanelPng from '../assets/solarPanel.png';
import waterExtracterPng from '../assets/waterExtracter.png';
import towerPng from '../assets/tower.png';

// 配置化的场景物体；按需在这里新增/调整。
const worldObjects = [
  {
    id: 'bed',
    name: '床',
    description: '柔软的休息舱，短暂小憩即可恢复精力。',
    angle: 0,
    textureKey: 'bed',
    texture: bedPng,
    scale: 0.4,
    yOffset: 8,
    depth: 0.4,
    interactive: true,
    action: 'sleep',
  },
  {
    id: 'table',
    name: '主机',
    description: '主控制台，显示星球系统状态与通信信息。',
    angle: 0.15,
    textureKey: 'table',
    texture: tablePng,
    scale: 0.4,
    yOffset: 6,
    depth: 0.45,
    interactive: false,
  },
  {
    id: 'billboard',
    name: '公告板',
    description: '任务公告与探险计划在此更新，别错过重要情报。',
    angle: -0.2,
    textureKey: 'billboard',
    texture: billboardPng,
    scale: 0.45,
    yOffset: 10,
    depth: 0.5,
    interactive: false,
  },
  {
    id: 'rocketBase',
    name: '火箭底座',
    description: '发射架底座，确保火箭垂直稳定并提供补给接口。',
    angle: -0.6,
    textureKey: 'rocketBase',
    texture: rocketBasePng,
    scale: 0.7,
    yOffset: 12,
    depth: 0.52,
    interactive: false,
  },
  {
    id: 'rocket',
    name: '火箭',
    description: '整装待发的运载火箭，随时可以启动新的星际旅程。',
    angle: -0.6,
    textureKey: 'rocket',
    texture: rocketPng,
    scale: 0.6,
    yOffset: -50,
    depth: 0.6,
    interactive: true,
    action: 'launch',
  },
  {
    id: 'kitchen',
    name: '厨房',
    description: '营地厨房，补给与热食的来源，保持探索者的战斗力。',
    angle: 0.5,
    textureKey: 'kitchen',
    texture: kitchenPng,
    scale: 0.45,
    yOffset: 8,
    depth: 0.48,
    interactive: false,
  },
  {
    id: 'musicPlayer',
    name: '音乐播放终端',
    description: '播发来自地球和火星的乐曲，驱散孤独与疲惫。',
    angle: 0.3,
    textureKey: 'musicPlayer',
    texture: musicPlayerPng,
    scale: 0.4,
    yOffset: 6,
    depth: 0.46,
    interactive: false,
  },
  {
    id: 'solarPanel',
    name: '太阳能板',
    description: '吸收星光转化能量，维持基地日常供电。',
    angle: 1.55,
    textureKey: 'solarPanel',
    texture: solarPanelPng,
    scale: 0.5,
    yOffset: 4,
    depth: 0.44,
    interactive: false,
  },
  {
    id: 'solarPanel',
    name: '太阳能板',
    description: '吸收星光转化能量，维持基地日常供电。',
    angle: 2,
    textureKey: 'solarPanel',
    texture: solarPanelPng,
    scale: 0.5,
    yOffset: 4,
    depth: 0.44,
    interactive: false,
  },
    {
  id: 'solarPanel',
  name: '太阳能板',
    description: '吸收星光转化能量，维持基地日常供电。',
  angle: 2.5,
  textureKey: 'solarPanel',
  texture: solarPanelPng,
    scale: 0.5,
    yOffset: 4,
    depth: 0.44,
    interactive: false,
  },
  {
    id: 'waterExtracter',
    name: '抽水站',
    description: '从星球深处提取可饮用的水源，生命保障的关键设施。',
    angle: 0.7,
    textureKey: 'waterExtracter',
    texture: waterExtracterPng,
    scale: 0.5,
    yOffset: 10,
    depth: 0.47,
    interactive: false,
  },
  {
    id: 'tower',
    name: '瞭望塔',
    description: '全景观测塔，监视天气与潜在威胁，保持安全。',
    angle: 2.2,
    textureKey: 'tower',
    texture: towerPng,
    scale: 0.55,
    yOffset: 12,
    depth: 0.5,
    interactive: false,
  },
];

export default worldObjects;
