import bedPng from '../assets/bed.png';
import tablePng from '../assets/table.png';
import billboardPng from '../assets/billboard.png';
import rocketBasePng from '../assets/rocketBase.png';
import rocketPng from '../assets/rocket.png';
import kitchenPng from '../assets/kitchen.png';
import musicPlayerPng from '../assets/musicPlayer.png';
import solarPanelPng from '../assets/solarPanel.png';
import waterExtracterPng from '../assets/waterExtracter.png';
import towerPng from '../assets/tower.png';
import robotPng from '../assets/robot.png';

// 配置化的场景物体；按需在这里新增/调整。
const worldObjects = [
  {
    id: 'bed',
    name: '床',
    description: '早睡早起才能每天都精神充沛。',
    angle: 0,
    textureKey: 'bed',
    texture: bedPng,
    scale: 0.4,
    yOffset: 8,
    depth: 0.4,
    interactive: true,
    action: 'sleep',
  },
  {
    id: 'table',
    name: '娱乐终端',
    description: '累了就看看电影吧！',
    angle: 0.15,
    textureKey: 'table',
    texture: tablePng,
    scale: 0.4,
    yOffset: 6,
    depth: 0.45,
    interactive: false,
    buttonConfig: {
      offsetY: 120,
      scale: 0.5,
    },
  },
  {
    id: 'billboard',
    name: '任务记录板',
    description: '每一天的快乐都值得被记录！',
    angle: -0.2,
    textureKey: 'billboard',
    texture: billboardPng,
    scale: 0.45,
    yOffset: 10,
    depth: 0.5,
    interactive: false,
    buttonConfig: {
      offsetY: 120,
      scale: 0.5,
      url: 'https://miro.com/app/board/uXjVJ_fU0kk=/',
    },
  },
  {
    id: 'rocketBase',
    name: '火箭底座',
    description: '发射架底座，确保火箭垂直稳定并提供补给接口。',
    angle: -0.6,
    textureKey: 'rocketBase',
    texture: rocketBasePng,
    scale: 0.7,
    yOffset: 12,
    depth: 0.52,
    interactive: false,
  },
  {
    id: 'rocket',
    name: '火箭',
    description: '火箭仍在维修中，准备好后即可发射返回地球。',
    angle: -0.6,
    textureKey: 'rocket',
    texture: rocketPng,
    scale: 0.6,
    yOffset: -50,
    depth: 0.6,
    interactive: true,
    action: 'launch',
  },
  {
    id: 'kitchen',
    name: '厨房',
    description: '营地厨房，补给与热食的来源，保持探索者的战斗力。',
    angle: 0.5,
    textureKey: 'kitchen',
    texture: kitchenPng,
    scale: 0.45,
    yOffset: 8,
    depth: 0.48,
    interactive: false,
  },
  {
    id: 'musicPlayer',
    name: '音乐播放终端',
    description: '火星也有音乐！',
    angle: 0.3,
    textureKey: 'musicPlayer',
    texture: musicPlayerPng,
    scale: 0.4,
    yOffset: 6,
    depth: 0.46,
    interactive: false,
    buttonConfig: {
      offsetY: 120,
      scale: 0.5,
    },
  },
  {
    id: 'solarPanel',
    name: '太阳能板',
    description: 'Phobos基地的能源也来自火星的太阳能。',
    angle: 1.55,
    textureKey: 'solarPanel',
    texture: solarPanelPng,
    scale: 0.5,
    yOffset: 4,
    depth: 0.44,
    interactive: false,
  },
  {
    id: 'solarPanel',
    name: '太阳能板',
    description: 'Phobos基地的能源也来自火星的太阳能。',
    angle: 2,
    textureKey: 'solarPanel',
    texture: solarPanelPng,
    scale: 0.5,
    yOffset: 4,
    depth: 0.44,
    interactive: false,
  },
    {
  id: 'solarPanel',
  name: '太阳能板',
    description: 'Phobos基地的能源也来自火星的太阳能。',
  angle: 2.5,
  textureKey: 'solarPanel',
  texture: solarPanelPng,
    scale: 0.5,
    yOffset: 4,
    depth: 0.44,
    interactive: false,
  },
  {
    id: 'waterExtracter',
    name: '抽水站',
    description: '别忘了给基地补充水分，当然更重要的是你也要多喝水！',
    angle: 0.7,
    textureKey: 'waterExtracter',
    texture: waterExtracterPng,
    scale: 0.5,
    yOffset: 10,
    depth: 0.47,
    interactive: false,
    waterButton: {
      offsetY: 120,
      scale: 0.5,
    },
    buttonConfig: {
      offsetY: 120,
      scale: 0.5,
    },
  },
  {
    id: 'tower',
    name: '瞭望塔',
    description: '全景观测塔，监视天气与潜在威胁，保持安全。',
    angle: 2.2,
    textureKey: 'tower',
    texture: towerPng,
    scale: 0.55,
    yOffset: 12,
    depth: 0.5,
    interactive: false,
  },
  {
    id: 'robot',
    name: '机器人',
    description: 'DAGU-1 机器人助手，陪伴并协助探索任务。点击它可以加载新的对话。',
    angle: -0.33,
    textureKey: 'robot',
    texture: robotPng,
    scale: 0.45,
    yOffset: 8,
    depth: 0.48,
    interactive: false,
  },
];

export default worldObjects;
