import bedPng from '../assets/bed.png';
import tablePng from '../assets/table.png';
import billboardPng from '../assets/billboard.png';
import rocketBasePng from '../assets/rocketBase.png';
import rocketPng from '../assets/rocket.png';
import kitchenPng from '../assets/kitchen.png';
import musicPlayerPng from '../assets/musicPlayer.png';
import solarPanelPng from '../assets/solarPanel.png';
import waterExtracterPng from '../assets/waterExtracter.png';
import towerPng from '../assets/tower.png';

// 配置化的场景物体；按需在这里新增/调整。
const worldObjects = [
  {
    id: 'bed',
    name: '床',
    angle: 0,
    textureKey: 'bed',
    texture: bedPng,
    scale: 0.4,
    yOffset: 8,
    depth: 0.4,
    interactive: true,
    action: 'sleep',
  },
  {
    id: 'table',
    name: '主机',
    angle: 0.15,
    textureKey: 'table',
    texture: tablePng,
    scale: 0.4,
    yOffset: 6,
    depth: 0.45,
    interactive: false,
  },
  {
    id: 'billboard',
    name: '公告板',
    angle: -0.2,
    textureKey: 'billboard',
    texture: billboardPng,
    scale: 0.45,
    yOffset: 10,
    depth: 0.5,
    interactive: false,
  },
  {
    id: 'rocketBase',
    name: '火箭底座',
    angle: -0.6,
    textureKey: 'rocketBase',
    texture: rocketBasePng,
    scale: 0.7,
    yOffset: 12,
    depth: 0.52,
    interactive: false,
  },
  {
    id: 'rocket',
    name: '火箭',
    angle: -0.6,
    textureKey: 'rocket',
    texture: rocketPng,
    scale: 0.6,
    yOffset: -50,
    depth: 0.6,
    interactive: true,
    action: 'launch',
  },
  {
    id: 'kitchen',
    name: '厨房',
    angle: 0.5,
    textureKey: 'kitchen',
    texture: kitchenPng,
    scale: 0.45,
    yOffset: 8,
    depth: 0.48,
    interactive: false,
  },
  {
    id: 'musicPlayer',
    name: '音乐播放终端',
    angle: 0.3,
    textureKey: 'musicPlayer',
    texture: musicPlayerPng,
    scale: 0.4,
    yOffset: 6,
    depth: 0.46,
    interactive: false,
  },
  {
    id: 'solarPanel',
    name: '太阳能板',
    angle: 1.55,
    textureKey: 'solarPanel',
    texture: solarPanelPng,
    scale: 0.5,
    yOffset: 4,
    depth: 0.44,
    interactive: false,
  },
  {
    id: 'solarPanel',
    name: '太阳能板',
    angle: 2,
    textureKey: 'solarPanel',
    texture: solarPanelPng,
    scale: 0.5,
    yOffset: 4,
    depth: 0.44,
    interactive: false,
  },
    {
    id: 'solarPanel',
    name: '太阳能板',
    angle: 2.5,
    textureKey: 'solarPanel',
    texture: solarPanelPng,
    scale: 0.5,
    yOffset: 4,
    depth: 0.44,
    interactive: false,
  },
  {
    id: 'waterExtracter',
    name: '抽水站',
    description: '没有水的话这个星球的生存保障系统就无法生存。当然，勇敢的探险者，你也一样！',
    angle: 0.7,
    textureKey: 'waterExtracter',
    texture: waterExtracterPng,
    scale: 0.5,
    yOffset: 10,
    depth: 0.47,
    interactive: false,
  },
  {
    id: 'tower',
    name: '瞭望塔',
    angle: 2.2,
    textureKey: 'tower',
    texture: towerPng,
    scale: 0.55,
    yOffset: 12,
    depth: 0.5,
    interactive: false,
  },
];

export default worldObjects;
